apiVersion: appconnect.ibm.com/v1beta1
kind: DesignerAuthoring
metadata:
  name: des
  namespace: cp4i
spec:
  couchdb:
    replicas: 1
    storage:
      size: 10Gi
      type: persistent-claim
      class: ibmc-file-gold-gid
  designerFlowsOperationMode: local
  license:
    accept: true
    license: L-KSBM-CJ2KWU
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  useCommonServices: true
  version: '12.0'
