apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  name: apic
  labels:
    app.kubernetes.io/instance: apiconnect
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: apiconnect-small
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-GVEN-GFUPVE
    metric: VIRTUAL_PROCESSOR_CORE
    use: production
  endpointTypes:
    - APIs
    - Events
  analytics:
    storage:
      enabled: true
      type: shared
  profile: n1xc7.m48
  version: 10.0.5.2
  storageClassName: ibmc-block-gold
